Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: numbers.GraphQLHandler
      CodeUri: /Users/t.russu/personal-workspace/RomanArabicConverter/serverless-functions
      Runtime: java11
      Architectures:
        - x86_64